export enum StatusEffectType {
  burn = "burn",
  brittle = "brittle",
  poison = "poison",
  shock = "shock",
  bleed = "bleed",
  stun = "stun",
  silence = "silence",
  taunt = "taunt",
  shield = "shield",
  haste = "haste",
  slow = "slow",
  confusion = "confusion",
  disarm = "disarm",
}
